version: '2'
services:
  proxy:
    build: proxy
    ports:
      - "80:80"

  hello:
    build: hello

  api-rs:
    build: api-rs
    volumes:
      - ./api-rs/app:/application

#  api-ds:
#    build: api-ds

  ui:
    build: ui
    volumes:
      - ./ui/src:/application/src

#  cassandra:
#    image: cassandra
#
